### ISSUE TITLE
Evaluation Metrics.

### ISSUE THREAD

**Issue by houjie8888** [boschresearch/ALDM#1]
Hi author, could you please provide the code for the evaluation calculation?

**Comment by houjie8888** [comment]
I would like to ask you a question about calculating the metrics during the training process. Specifically, the training process is usually interspersed with a validation step, do you perform the computation of the evaluation metrics during the validation step, which seems to be time consuming. So I'm wondering how you schedule the evaluation during the training process?

**Comment by YumengLi007** [comment]
Hi @houjie8888 ,  

we used [clean-fid](https://github.com/GaParmar/clean-fid) for FID evaluation, [tifa-score](https://github.com/Yushi-Hu/tifa) for measuring text controllability (see a script example here [tifa_eval.txt](https://github.com/boschresearch/ALDM/files/14006756/tifa_eval.txt)). For mIoU evaluation, following prior works, we used pretrained [DRN-D-105](https://github.com/fyu/drn) and [UperNet101](https://github.com/CSAILVision/semantic-segmentation-pytorch) for Cityscapes and ADE20K, respectively. The pretrained segemnters can be found from their repos, i.e., [drn](https://drive.google.com/drive/folders/1fIsCB877l37cFAJomoQzNrEYPqwMwZ4Q), [upernet-encoder](http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet101-upernet/encoder_epoch_50.pth) and [upernet-decoder](http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet101-upernet/decoder_epoch_50.pth).

Hope this helps :)

**Comment by houjie8888** [comment]
@ct2034  Thank you very much for your reply!

So, the quantitative evaluation is only done once at the end of the training.
