### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by MalekSamet** [boschresearch/ALDM#13]
/ALDM/cldm_seg/util.py", line 41, in forward
    seg_emb = torch.index_select(self.class_embeddings, 0, seg_map_.cpu())
IndexError: index out of range in self

I am using the structure of cityscapes.py for my new dataset, where I am using self.lb_map = {el['id']: el['trainId'] for el in labels_info}
I created a json file "newdataset_info.json" where I packed :
{
        "name": "terrain",
        "ignoreInEval": false,
        "id": 30,
        "color": [
            112,
            9,
            255
        ],
        "trainId": 30
    }
    for each class. Note that I put all my classes and I am not ignoring any of them (No trainId = 255).
    When I run the code, I receive this error (See above).
However, I tried to add 3 fictive classes to the json file, named them randomly but put their trainId as 255, it worked. I dont understand what is the problem here? And I don't know if the way it made the program compile is true and does not affect the training?

**Comment by YumengLi007** [comment]
you probably need to check the \_\_get_item\_\_ function in the dataloader. For instance, you maybe don't need https://github.com/boschresearch/ALDM/blob/9abb0833f1dbb6a2762a21d22a6e84f84f195328/dataloader/cityscapes.py#L250 if there is no trainID=255
