### ISSUE TITLE
Inquiry about GPU Training Time

### ISSUE THREAD

**Issue by huamiao1012** [boschresearch/ALDM#14]
Thank you for your incredible work！I would like to ask about the GPU training time required for the model.  Additionally, could you please provide guidance on how to find the evaluation functions for mIOU and FID?

**Comment by YumengLi007** [comment]
Hi @huamiao1012 , thanks for your interests! The model is trained with 2 A100 for 3-5 days depending on the dataset size. 
For FID evaluation, we used the implementation [here](https://github.com/mseitzer/pytorch-fid). For mIoU evaluation, we used pretrained [DRN](https://github.com/fyu/drn) and [UperNet101](https://github.com/CSAILVision/semantic-segmentation-pytorch) segmentation networks for Cityscapes and ADE20K dataset, respectively.

**Comment by huamiao1012** [comment]
Thank you for your reply! I got it.
