### ISSUE TITLE
Cannot Training with Released Code

### ISSUE THREAD

**Issue by liming-ai** [boschresearch/ALDM#3]
Thanks for your contributions and open-source code.

When I try to reproduce training with the command:
```bash
bash bash_script/train_ade20k.sh
```

these errors happened:
```bash
FileNotFoundError: [Errno 2] No such file or directory: 
'/fs/scratch/rng_cr_bcai_dl/lyu7rng/0_project_large_models/code_repo/0_ControlNet/checkpoint/control_seg_enc_scratch.ckpt'
```

```
FileNotFoundError: [Errno 2] No such file or directory: 
'/fs/scratch/rng_cr_bcai_dl/lyu7rng/0_project_large_models/pretrained/ade20k_semseg/upernet101/encoder_epoch_50.pth'
```

Could you please provide these checkpoints and provide instructions of how to train ALDM?

**Comment by wangjin1234567891** [comment]
I have the same problem. Have you solved it？

**Comment by YumengLi007** [comment]
Hi, the model checkpoints, e.g., encoder_epoch_50.ckpt is provided in [here](https://huggingface.co/Yumeng/ALDM/tree/main)

**Comment by wangjin1234567891** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 
'/fs/scratch/rng_cr_bcai_dl/lyu7rng/0_project_large_models/code_repo/0_ControlNet/checkpoint/control_seg_enc_scratch.ckpt'

**Comment by wangjin1234567891** [comment]
I haven't seen this.

**Comment by YumengLi007** [comment]
They are initially randomly initialized weights similar to the newly added branch in ControlNet. I will upload mine later today :)

**Comment by wangjin1234567891** [comment]
OK，thanks.

**Comment by YumengLi007** [comment]
[control_seg_enc_scratch.ckpt](https://huggingface.co/Yumeng/ALDM/blob/main/control_seg_enc_scratch.ckpt) has been uploaded :)
