### ISSUE TITLE
optimizer_idx

### ISSUE THREAD

**Issue by wangjin1234567891** [boschresearch/ALDM#4]
![image](https://github.com/boschresearch/ALDM/assets/76192707/a7d2b3fe-1877-4462-9428-7b2462e7e8ca)
I have a problem. Can you help me solve it？

**Comment by YumengLi007** [comment]
maybe remove the optimizer_idx arguement in the following line?
https://github.com/boschresearch/ALDM/blob/6360607957e038ec0c8ea656572dc6f56009157c/cldm_seg/cldm_seg_pixel_seg_enc_multiStep.py#L753

btw, the code is fine when using pytorch-lightning==1.4.2, if removing it cannot fix, maybe check the pytorch-lightning version :)

**Comment by wangjin1234567891** [comment]
![image](https://github.com/boschresearch/ALDM/assets/76192707/5557f865-bff0-407c-940d-e484bcca459c)
Thanks, I changed pytorch-lightning from 1.5.0 to 1.4.2, that issue disappeared, but a new issue came up

**Comment by wangjin1234567891** [comment]
That's taken care of, thank you.
