### ISSUE TITLE
Training code / weight for COCO

### ISSUE THREAD

**Issue by 1211sh** [boschresearch/ALDM#5]
Hi, 
could you please provide the code for training COCO (e.g., dataloader, segmenter config) or weight file of COCO?

Thank you.

**Comment by YumengLi007** [comment]
Hi @1211sh , thanks for your interests!
We have not actively experimented with COCO dataset. I can work on collecting code related to COCO and go through the approval process of the open sourcing (e.g., code scan). 
Meanwhile, maybe you could try out the checkpoint trained on ADE20K? Thank you :)

**Comment by 1211sh** [comment]
Thanks a lot for your quick reply and sincere help.

I have already tested on Ade20K, and I think it would be even more meaningful for the research community if possible with the COCO dataset, given the good results of your research. :)

**Comment by YumengLi007** [comment]
Hi @1211sh I have uploaded the checkpoint [here](https://huggingface.co/Yumeng/ALDM/blob/main/coco_step9.ckpt), and updated the code and README file, please have a look :) You should be able to generate images using [bash_script/generate_coco.sh](https://github.com/boschresearch/ALDM/blob/a07abb8616311d558fcbb36d5f5c064555786669/bash_script/generate_coco.sh)

**Comment by 1211sh** [comment]
Hi, I have found out the code with the new checkpoint is working well. Thanks a lot!

**Comment by 1211sh** [comment]
Dear sir,
I found that 'decoder_epoch_50_172cls.pth' is missing in https://huggingface.co/Yumeng/ALDM/tree/main.
Could you please provide the weight?

Thank you.

**Comment by YumengLi007** [comment]
Hi @1211sh , please find the model [here](https://huggingface.co/Yumeng/ALDM/blob/main/decoder_epoch_50_172cls.pth)
