### ISSUE TITLE
Need for captions for new dataset?

### ISSUE THREAD

**Issue by yassine9666** [boschresearch/ALDM#9]
I want to train the model on another urban dataset. One folder should contain the segmentation masks and the other the images right? 
Also, do I need the caption.json for my new dataset?
Thank you :)

**Comment by YumengLi007** [comment]
Hi @yassine9666 , you would need the captions for training. You could using some VL-captioning models, e.g., BLIP, LLaVA, to get the caption :)

**Comment by jianlufu121** [comment]
> I want to train the model on another urban dataset. One folder should contain the segmentation masks and the other the images right? Also, do I need the caption.json for my new dataset? Thank you :)

Hi @yassine9666 ,have you generated the `caption.json` file for your new dataset? If so, could you please share the specific method you used for generating it?
